services:
  # Run before deploying the API:
  # docker compose --profile migrate run --rm pump-api-migrate
  pump-api-migrate:
    image: ghcr.io/thesaiteja24/pump-api:latest
    profiles: [migrate]
    env_file: .env
    command: [bun, run, migrate:deploy]

  pump-api:
    image: ghcr.io/thesaiteja24/pump-api:latest
    container_name: pump-api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, 'http://localhost:${PORT}/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
