version: '3.8'

services:
  test-postgres:
    image: postgres:15-alpine
    container_name: pump-fastify-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pump_fastify_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    container_name: pump-fastify-test-redis
    ports:
      - '6380:6379'

volumes:
  postgres_test_data:
