services:
  test-postgres:
    image: postgres:17-alpine
    container_name: pump-test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pump_test
    ports:
      - '9003:5432'
    volumes:
      - pump_test_postgres_data:/var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    container_name: pump-test-redis
    ports:
      - '9004:6379'

volumes:
  pump_test_postgres_data:
