services:
  # 1. The Main API Web Service
  - type: web
    name: pump-api
    runtime: node
    buildCommand: bun install && bunx prisma generate && bun run build
    startCommand: bun run migrate:deploy && bun run start

