name: Cron Reminders

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -X POST https://pump.thesaiteja.dev/api/v1/cron/reminders-dispatch \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
